{{- $values := .Values }}
{{- if $values.alerts.enabled }}
{{- range $target, $unused := $values.alerts.prometheus }}
{{- range $path, $bytes := $.Files.Glob (printf "alerts/%s/*.alerts" $target) }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

metadata:
  name: {{ printf "%s" $path | replace "/" "-" }}
  labels:
    app: limes-api
    tier: os
    type: alerting-rules
    prometheus: {{ index $values.alerts.prometheus $target | required (printf "$values.alerts.prometheus.%s missing" $target) }}

spec:
{{ printf "%s" $bytes | indent 2 }}

{{- end }}
{{- end }}

---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule

# This rule is in here, rather than in a file in alerts/, because we need to use templating.
metadata:
  name: alerts-roleassignment.alerts
  labels:
    app: limes-api
    tier: os
    type: alerting-rules
    prometheus: {{ required ".Values.alerts.prometheus.openstack missing" $values.alerts.prometheus.openstack }}

spec:
  groups:
  - name: openstack-limes-roleassignment.alerts
    rules:
        # allowed role assignments for the `resource_service` role:
        # - user admin@Default in project admin@Default (openstack-seeder assigns network/DNS quota during build-up)
        # - user limes@Default in project cloud_admin@ccadmin
        # HOWEVER admin@Default is covered by a system role assignment that does not count towards this metric
        - alert: OpenstackLimesUnexpectedServiceRoleAssignments
          expr: max(openstack_assignments_per_role{role_name="resource_service"}) > 1
          for: 10m
          labels:
            support_group: containers
            tier: os
            service: limes
            severity: info
            playbook: 'docs/support/playbook/unexpected-role-assignments'
            meta: 'Unexpected role assignments found for Keystone role "resource_service"'
          annotations:
            summary: 'Unexpected role assignments'
            description: 'The Keystone role "resource_service" is assigned to more users/groups than expected.'

        # allowed role assignments for the `cloud_resource_admin` role:
        # - group CCADMIN_CLOUD_ADMINS@ccadmin in project cloud_admin@ccadmin
        # - user dashboard@Default             in project cloud_admin@ccadmin (TODO: remove once the seed changes were deployed)
        # - user kubernikus-terraform@Default  in project cloud_admin@ccadmin (TODO: remove once the seed changes were deployed)
        # - user TCC_BM_ANSL@ccadmin           in project cloud_admin@ccadmin
        # - user TCC_BM_TMPR@ccadmin           in project cloud_admin@ccadmin
        - alert: OpenstackLimesUnexpectedCloudAdminRoleAssignments
          expr: max(openstack_assignments_per_role{role_name="cloud_resource_admin"}) > 5
          for: 10m
          labels:
            support_group: containers
            tier: os
            service: limes
            severity: info
            playbook: 'docs/support/playbook/unexpected-role-assignments'
            meta: 'Unexpected role assignments found for Keystone role "cloud_resource_admin"'
          annotations:
            summary: 'Unexpected role assignments'
            description: 'The Keystone role "cloud_resource_admin" is assigned to more users/groups than expected.'

        # allowed role assignments for the `cloud_resource_viewer` role:
        # - user billing@Default                         in project billing@ccadmin (for data transfer from Limes to CBR)
        # - user $IBP_READONLY/$PLUTUS_READONLY@Dccadmin in project cloud_admin@ccadmin (for data transfer from Limes to IBP/Plutus, see billing-seed for details)
        # - group CCADMIN_CLOUD_ADMINS@ccadmin           in project cloud_admin@ccadmin
        - alert: OpenstackLimesUnexpectedCloudViewerRoleAssignments
          expr: max(openstack_assignments_per_role{role_name="cloud_resource_viewer"}) > 3
          for: 10m
          labels:
            support_group: containers
            tier: os
            service: limes
            severity: info
            playbook: 'docs/support/playbook/unexpected-role-assignments'
            meta: 'Unexpected role assignments found for Keystone role "cloud_resource_viewer"'
          annotations:
            summary: 'Unexpected role assignments'
            description: 'The Keystone role "cloud_resource_viewer" is assigned to more users/groups than expected.'

{{- end }}
