apiVersion: v1
kind: Secret
metadata:
  name: arista-exporter
  namespace: {{ .Values.arista_exporter.namespace }}
  labels:
    app: arista-exporter
    type: exporter
data:
    redfish_username: {{ required ".Values.global.arista_username" .Values.global.arista_username | b64enc | quote }}
    redfish_password: {{ required ".Values.global.arista_password" .Values.global.arista_password | b64enc | quote }}
