{{- range $key, $host := .Values.hosts }}
---
apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: {{ $key }}
  namespace: {{ $.Release.namespace }}
  labels:
    kubernetes.metal.cloud.sap/bb: {{ $host.bb }}
    kubernetes.metal.cloud.sap/type: {{ default "metal" $host.type }}
    kubernetes.metal.cloud.sap/az: {{ $host.az }}
    kubernetes.metal.cloud.sap/flavor: {{ $host.flavor }}
spec:
  online: {{ default "True" $host.online }}
  bmc:
    address: {{ $host.redfishUrl }}
    credentialsName: bmc-secret-{{ $key }}
    disableCertificateVerification: {{ default "True" $host.disableCertificateVerification }}
  bootMACAddress: {{ $host.bootMac }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: bmc-secret-{{ $key }}
  namespace: {{ $.Release.namespace }}
data:
  username: {{ default $.Values.remoteboard.username $host.username | b64enc }}
  password: {{ default $.Values.remoteboard.password $host.password | b64enc }}
{{- end }}
