---
apiVersion: v1
kind: Service
metadata:
  name: ironic
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: dhcp-{{ .Values.ironic.dhcpServerPort }}
    port: {{ .Values.ironic.dhcpServerPort }}
    protocol: UDP
    targetPort: {{ .Values.ironic.dhcpServerPort }}
    nodePort: 30671
  - name: dhcp-{{ .Values.ironic.dhcpClientPort }}
    port: {{ .Values.ironic.dhcpClientPort }}
    protocol: UDP
    targetPort: {{ .Values.ironic.dhcpClientPort }}
    nodePort: 30672
  - name: tftp
    port: {{ .Values.ironic.tftpPort }}
    protocol: UDP
    targetPort: {{ .Values.ironic.tftpPort }}
    nodePort: 30673
  - name: ipxe
    port: {{ .Values.ironic.ipxePort }}
    protocol: TCP
    targetPort: {{ .Values.ironic.ipxePort }}
    nodePort: 30674
  - name: ironic
    port: {{ .Values.ironic.ironicPort }}
    protocol: TCP
    targetPort: {{ .Values.ironic.ironicPort }}
    nodePort: 30675
  - name: inspector
    port: {{ .Values.ironic.inspectorPort }}
    protocol: TCP
    targetPort: {{ .Values.ironic.inspectorPort }}
    nodePort: 30676
  selector:
    name: ironic
  type: NodePort
