alerts:
  enabled: false
  prometheus:
    - name: infra-frontend
      type: prometheus
    - name: kubernetes
      type: prometheus
  cisco: false
  global: false
  queue: false
  postfix: false
owner-info:
  helm-chart-url: "https://github.com/sapcc/helm-charts/tree/master/prometheus-exporters/cronus-openstack-alerts"
  support-group: email