apiVersion: v1
kind: Secret

metadata:
  name: api-conf
  namespace: hermes
  labels:
    app: hermes-api

data:
  hermes.conf: {{ include (print .Template.BasePath "/_hermes.conf.tpl") . | b64enc }}
