mappedOrgAdminIdPGroup:

teams: {}
  # team1:
  #   description: Team number 1
  #   mappedIdPGroup: Identity provider group name.
  #   isSupportGroup: true|false

teamRoleBindings: []
  # - teamRef: team1
  #   teamRoleRef: role1
  #   clusterNames:
  #     - cluster1

oidc:
  issuer:
  redirectURL:
  clientID:
  clientSecret:

alerts:
  enabled: false
  # Supernova options.
  endpoint:
  filterLabels:
    - app
    - cluster
    - cluster_type
    - context
    - job
    - region
    - service
    - severity
    - status
    - support_group
    - tier
    - type
  silenceExcludedLabels:
    - pod
    - pod_name
    - instance
  predefinedFilters: 
    - name: "prod"
      displayName: "Prod"
      matchers:
        region: "^(?!qa-de-).*"
    - name: "prod-qa"
      displayName: "Prod + QA"
      matchers:
        region: "^(?!qa-de-(?!1$)\\d+).*"
    - name: "labs"
      displayName: "Labs"
      matchers:
        region: "^qa-de-(?!1$)\\d+"
      - name: "all"
      displayName: "All"
      matchers:
        region: ".*"  
  # silenceTemplates: --> defined in the _silence.conf.tpl
    
  # Alertmanager options.
  alertmanager:
    # Do not deploy the alertmanager.
    enabled: false

teams2slack:
  displayName: Slack
  enabled: false
  dryRun: false
  endpoint:
  infoChannelID:
  slackToken:
  groupNamePrefix: CCloud
  groupNameSuffix: greenhouse-team

doop:
  enabled: false
  displayName: Violations
  apiEndpoint:
  showDebugSeverities: false

doopKubernikus:
  enabled: false
  displayName: Kubernikus
  apiEndpoint:
  showDebugSeverities: false

heureka:
  enabled: false
  displayName: Heureka
  apiEndpoint:
