{{- if and .Values.auth.username .Values.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-memcached-secrets
  labels:
    type: configuration
    application: {{ .Release.Name }}
data:
  memcached-sasl-db: |
    "{{ .Values.auth.username }}:{{ .Values.auth.password }}"
{{- end }}
