apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    system: openstack
    application: {{ .Release.Name }}
type: Opaque
data: 
  secrets.conf: |
    {{ tpl (.Files.Get "secrets/_secrets.conf") . | b64enc | indent 4 }}
