apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    system: openstack
    application: {{ .Release.Name }}
type: Opaque
data: 
  secrets.conf: |
    {{ tpl (.Files.Get "etc/secrets.conf") . | indent 4 | b64enc }}
