{{- if .Values.unbound.bind_rpz_proxy.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: bind-rpz-proxy-secrets
type: Opaque

stringData:
  rndc.key: |
    key {{ default "rndc-key" .Values.unbound.bind_rpz_proxy.rndc.keyname | quote }} {
      algorithm {{ default "hmac-sha512" .Values.unbound.bind_rpz_proxy.rndc.algo | quote }};
      secret {{ .Values.unbound.bind_rpz_proxy.rndc.secret | quote }};
    };
  tsig.key: |
    key {{ .Values.unbound.rpz.tsig.keyname | quote }} {
      algorithm {{ default "hmac-sha512" .Values.unbound.rpz.tsig.algo | quote }};
      secret {{ .Values.unbound.rpz.tsig.secret | quote }};
    };
{{- end }}
