{{- if .Values.updater.api.enabled }}
kind: Service
apiVersion: v1

metadata:
  name: {{ include "fullname" . }}
  namespace: {{ .Values.updater.namespace }}
  labels:
    app: {{ include "fullname" . }}
    type: service

spec:
  type: ClusterIP
  selector:
    name: {{ include "fullname" . }}
  ports:
  - name: {{ include "fullname" . }}
    port: {{.Values.updater.api.port}}
    targetPort: {{ include "fullname" . }}
    protocol: TCP
{{- end}}