apiVersion: v2
description: A Helm chart for SAP's CCloud Plutono 7.5.x deployment
name: plutono
version: 0.3.0
dependencies:
  - name: postgresql-ng
    alias: postgresql
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.0.11
  - name: pgbackup
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.44
    condition: pgbackup.enabled
  - name: owner-info
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.0
  - name: prometheus-monitors
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.0.2
