---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "postgres.fullname" . }}-etc
data:
  postgresql.conf: |
    {{- include (print .Template.BasePath "/_postgresql.conf.tpl") . | nindent 4 }}

{{- if (hasKey .Values "sqlOnCreate") }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "postgres.fullname" . }}-sql-on-create
data:
  on-create.sql: |
    {{ .Values.sqlOnCreate }}
{{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "postgres.fullname" . }}-sql-on-startup
data:
  on-startup.sql: |
    {{- /* duplicated with the code in rbac because the templating is to limited in its features */}}
    {{- $users := .Values.users }}
    {{- if .Values.persistence.createBackupUser }}
      {{- $users := merge $users (dict "backup" (dict)) }}
    {{- end }}
    {{- if .Values.createMetricsUser }}
      {{- $users := merge $users (dict "metrics" (dict)) }}
    {{- end }}

    SET password_encryption = '{{ if ge ($.Values.postgresVersion | int) 12 }}scram-sha-256{{ else }}md5{{ end }}';

    {{- if lt ($.Values.postgresVersion | int) 14 }}
    SELECT 'CREATE ROLE "poor_mans_pg_read_all_data"' where not exists (select rolname from pg_authid where rolname = 'poor_mans_pg_read_all_data')\gexec
    {{- else }}
    DROP ROLE IF EXISTS poor_mans_pg_read_all_data;
    {{- end }}

    {{- range $user, $settings := $users }}
    {{- /* prevent more suffering and pain by forgotten {} in users */}}
    {{- $settings = $settings | default (dict) }}
    SELECT 'CREATE ROLE "{{ $user }}" WITH PASSWORD ''%USER_PASSWORD_{{ $user | replace "-" "_" }}%'' LOGIN' where not exists (select rolname from pg_authid where rolname = '{{ $user }}')\gexec
    {{- /* update password in case it changed or the password hashing format changed */}}
    ALTER USER "{{ $user }}" WITH PASSWORD '%USER_PASSWORD_{{ $user | replace "-" "_" }}%';

    {{- if not (eq $user "backup" "metrics") }}
    -- https://www.postgresql.org/docs/current/ddl-priv.html
    GRANT CREATE,CONNECT,TEMPORARY ON DATABASE "%PGDATABASE%" TO "{{ $user }}";
    GRANT SELECT,INSERT,UPDATE,DELETE,TRUNCATE,REFERENCES,TRIGGER ON ALL TABLES IN SCHEMA public TO "{{ $user }}";
    {{- end }}

    {{- range $settings.grant }}
    {{ . }} to "{{ $user }}";
    {{- end }}

    {{- if $settings.setOwner }}
    ALTER DATABASE "%PGDATABASE%" OWNER TO "{{ $user }}";
    SELECT format('ALTER TABLE %I.%I.%I OWNER TO %I;', table_catalog, table_schema, table_name, '{{ $user }}')
      FROM information_schema.tables
      WHERE table_schema = '%PGDATABASE%';
    {{- end }}

    {{- if eq $user "backup" }}
    GRANT CONNECT ON DATABASE "%PGDATABASE%" TO backup;

    {{ if ge ($.Values.postgresVersion | int) 14 }}
    GRANT pg_read_all_data to backup;
    {{- else }}
    GRANT poor_mans_pg_read_all_data to backup;
    {{- end }}
    {{- end }}

    {{- if eq $user "metrics" }}
    GRANT pg_monitor to metrics;
    ALTER USER metrics SET SEARCH_PATH TO postgres_exporter,pg_catalog;
    {{- if ge ($.Values.postgresVersion | int) 14 }}
    GRANT pg_read_all_data to metrics;
    {{- else }}
    GRANT poor_mans_pg_read_all_data to metrics;
    {{- end }}
    {{- end }}
    {{- end }}

    {{ .Values.sqlOnStartup }}
