apps:
  apod:
    enabled: false
  cinder:
    enabled: false
  manila:
    enabled: false

harvest:
  image:
    repository: rahulguptajss/harvest
    tag: 23.11.0-1
  loglevel: 2
  ports:
    liveness: 8080
    prometheus: 13000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

netappsd:
  image:
    repository: netappsd
    tag: v2-20240313103014
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
