apps:
  apod:
    enabled: false
    objects: []
  cinder:
    enabled: false
    objects:
      Lun: lun.yaml
      ISCSISession: iscsi_session.yaml
  manila:
    enabled: false
    objects:
      LIF: lif.yaml
      NFSClients: nfs_clients.yaml
      SnapMirror: snapmirror.yaml
      Snapshot: custom_snapshot.yaml

harvest:
  image:
    repository: rahulguptajss/harvest
    tag: 23.11.0-1
  loglevel: 2
  ports:
    liveness: 8080
    metrics: 13000
  resources:
    requests:
      cpu: 50m
      memory: 128Mi

netappsd:
  image:
    repository: netappsd
    tag: v2-20241001095016
  ports:
    metrics: 8000
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
