name: pgbackup
version: 1.1.7 # this version number is SemVer as it gets used to auto bump
apiVersion: v2
description: PostgreSQL backup/restore pod
appVersion: "v0.10.0-61-g873b158" # of https://github.com/sapcc/backup-tools
