apiVersion: v1
kind: ConfigMap
metadata:
  name: barbican-scripts
  labels:
    system: openstack
    type: configuration
    component: barbican

data:
{{- if .Values.barbican_nanny.db_secret_move.enabled }}
  move-secrets.sh: |
{{ include (print .Template.BasePath "/scripts/_move-secrets.sh.tpl") . | indent 4 }}
{{- end}}