apiVersion: v2
description: Kube-System relevant addon collection.
name: kube-system-addons
version: 0.0.1
home: https://github.com/sapcc/helm-charts/tree/master/system/kube-system-metal
dependencies:
  - name: go-pmtud
    repository: https://charts.eu-de-2.cloud.sap
    version: 2.0.15
  - name: sysctl
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.0.9
  - name: toolbox-prepull
    repository: https://charts.eu-de-2.cloud.sap
    version: 1.0.7
  - name: kube-detective
    condition: kube-detective.enabled
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.0.2
  - name: kube-cni
    condition: kube-cni.enabled
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.0.4
  - name: owner-info
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.0
  - name: conntrack-nanny
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.1.4
