apiVersion: v1
description: Chart for Redis
name: redis

# NOTE: When upgrading please note the following changes:
#
# from 1.3.x
# - image.repository and metrics.image.repository as well as their
#   imagePullPolicy settings are now hardcoded.
# - The Redis image now comes from ccloud/shared-app-images/redis. Please update
#   your image.tag pins accordingly (see comment in values.yaml).
#
# from 1.4.x
# - the deployment will be rolled out (restarted) on password and configuration
#   Secrets changes.
# from 1.5.x
# - Switched from Redis to its fork Valkey because of the Redis license change.
#   The image now comes from ccloud/shared-app-images/valkey.
#   If you have image.tag pins (which we recommend against), please update them accordingly.
version: 1.6.0 # this version number is SemVer as it gets used to auto bump
