apiVersion: v2
name: thanos-scaleout
description: Deploy Thanos via operator 
type: application
version: 0.4.7
dependencies:
  - name: thanos
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.8.0
  - name: owner-info
    repository: https://charts.eu-de-2.cloud.sap
    version: 0.2.0
