{{- if index .Values "linkerd-control-plane" "enabled" }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: linkerd-destination-deployment
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources:
      - cpu
      - memory
      controlledValues: RequestsOnly
      maxAllowed:
        cpu: 1800m
        memory: "11833149358"
      minAllowed:
        cpu: 50m
        memory: 48Mi
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: linkerd-destination
  updatePolicy:
    updateMode: Initial
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: linkerd-identity-deployment
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources:
      - cpu
      - memory
      controlledValues: RequestsOnly
      maxAllowed:
        cpu: 3600m
        memory: "23666298716"
      minAllowed:
        cpu: 50m
        memory: 48Mi
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: linkerd-identity
  updatePolicy:
    updateMode: Initial
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: linkerd-proxy-injector-deployment
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources:
      - cpu
      - memory
      controlledValues: RequestsOnly
      maxAllowed:
        cpu: 3600m
        memory: "23666298716"
      minAllowed:
        cpu: 50m
        memory: 48Mi
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: linkerd-proxy-injector
  updatePolicy:
    updateMode: Initial
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: metrics-api-deployment
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources:
      - cpu
      - memory
      controlledValues: RequestsOnly
      maxAllowed:
        cpu: 7200m
        memory: "47332597432"
      minAllowed:
        cpu: 50m
        memory: 48Mi
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: metrics-api
  updatePolicy:
    updateMode: Initial
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: tap-deployment
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources:
      - cpu
      - memory
      controlledValues: RequestsOnly
      maxAllowed:
        cpu: 7200m
        memory: "47332597432"
      minAllowed:
        cpu: 50m
        memory: 48Mi
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tap
  updatePolicy:
    updateMode: Initial
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: tap-injector-deployment
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources:
      - cpu
      - memory
      controlledValues: RequestsOnly
      maxAllowed:
        cpu: 7200m
        memory: "47332597432"
      minAllowed:
        cpu: 50m
        memory: 48Mi
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tap-injector
  updatePolicy:
    updateMode: Initial
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: web-deployment
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: '*'
      controlledResources:
      - cpu
      - memory
      controlledValues: RequestsOnly
      maxAllowed:
        cpu: 7200m
        memory: "47332597432"
      minAllowed:
        cpu: 50m
        memory: 48Mi
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web
  updatePolicy:
    updateMode: Initial
{{- end }}
